using System;

namespace WealthTools.Library.BrokerManager
{
  
    public class SqlConstants
    {
        public const string READBROKERINFO_SQL = @"SELECT WBR.BROKER_ID, WBR.BROKER_NAME, WBR.BROKER_TITLE, WUS.USERNAME, WBR.FIRM_NAME, WBR.CLRG_FIRM_NAME, 
			    WBR.FIRM_PHONE, WBR.EMAIL_ADDRESS as FIRM_EMAIL, NULL as FIRM_FAX, 
                NVL ((SELECT external_id FROM web_team WHERE mark_deleted_yn = 'N' AND team_hierarchy_type_id = 1 CONNECT BY PRIOR parent_team_id = team_id START WITH team_id IN (SELECT primary_team_id FROM web_broker WHERE broker_id = :broker_id)), '-1' ) AS SUB_NO,
			   WBR.CLRG_FIRM_PHONE, NULL as CLRG_FIRM_EMAIL, NULL as CLRG_FIRM_FAX, 
			    WBR.FIRM_ADDRESS1 as FIRM_ADDR1, WBR.FIRM_ADDRESS2 as FIRM_ADDR2, 
                WBR.FIRM_CITY, WBR.FIRM_STATE, WBR.FIRM_ZIPCODE as FIRM_POSTAL_CODE, WBR.FIRM_COUNTRY, 
				  NVL((SELECT NAME FROM WEB_COUNTRY_NAME WHERE COUNTRY_CODE = NVL(WBR.FIRM_COUNTRY, 'US') AND LANGUAGE_ID = 0), '') AS FIRM_COUNTRY_NAME, 
			    WBR.CLRG_FIRM_ADDRESS1 as CLRG_FIRM_ADDR1, WBR.CLRG_FIRM_ADDRESS2 as CLRG_FIRM_ADDR2, 
			    WBR.CLRG_FIRM_CITY, WBR.CLRG_FIRM_STATE, WBR.CLRG_FIRM_ZIPCODE as CLRG_FIRM_POSTAL_CODE, WBR.CLRG_FIRM_COUNTRY, 
				  NVL((SELECT NAME FROM WEB_COUNTRY_NAME WHERE COUNTRY_CODE = NVL(WBR.CLRG_FIRM_COUNTRY, 'US') AND LANGUAGE_ID = 0), '') AS CLRG_COUNTRY_NAME, 
               WBR.INSTITUTION_ID, WBR.AFFILIATION, WBR.STATE as PRIMARY_STATE, WBR.DESIGNATION_SUFFIX 
			FROM WEB_BROKER WBR, WEB_USER WUS  
			WHERE 
			 WUS.USER_ID= WBR.BROKER_ID AND 
			BROKER_ID=:broker_id";
    }
}
